var tableauQuestion = [
    {   question : "Jesli jedziesz 65kmh, a zblizasz sie do strefy mieszkalniej musisz:",
        propositionA : "Przyspieszyc",
        propositionB : "Przyspieszyc i kogos przejechac",
        propositionC : "Zwolnic",
        propositionD : "Jechac tak samo jak teraz",
        reponse : "C"},

    {   question : "Jesli skrecasz w prawo na swiatlach, ale widzisz przejście dla pieszych, co robisz:",
        propositionA : "Przyspieszam i kogos potracam",
        propositionB : "Patrze co robia inni",
        propositionC : "Czekam az pieszy przejdzie",
        propositionD : "Wysiadasz z auta i strzelasz do pieszego",
        reponse : "C"},

    {   question : "Bez wcześniejszego znaku, ustalona prędkościa w obszarze mieszkalnym jest: __ kmh",
        propositionA : "30",
        propositionB : "Tyle ile chce",
        propositionC : "40",
        propositionD : "45",
        reponse : "A"},

  {   question : "Przed każdą zmianą pasa musisz:",
        propositionA : "Popatrzec w lusterka",
        propositionB : "Sprawdzic swoje martwe punkty",
        propositionC : "Wlaczyc kierunkowskaz",
        propositionD : "Wszystkie z powyzszych",
        reponse : "D"},

  {   question : "Ile procent alkocholu mozesz miec podczas jazdy?",
        propositionA : "0.05%",
        propositionB : "W C*uj",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "Kiedy mozesz jechac na swiatlach?",
        propositionA : "Kiedy chce, jestem rajdowcem",
        propositionB : "I tak nikt na nie nie patrzy",
        propositionC : "Kiedy jestes w strefie szkolnej",
        propositionD : "Kiedy jest zielony lub czerwony ale skręcasz w prawo",
        reponse : "D"},

  {   question : "Widac, ze pieszy sie spieszy ale to ty masz zielone swiatlo a on czerwone, co robisz?",
        propositionA : "Przepuszcam go",
        propositionB : "Otwieram okno i kazde mu sie ogarnac bo go odstrzele",
        propositionC : "Strzelam do niego",
        propositionD : "Jade bo mam zielone",
        reponse : "D"},

  {   question : "Co jest dozwolone gdy mijaja Cie inne pojazdy",
        propositionA : "Wszystko bo jestem rajdowcem",
        propositionB : "Zwalnianie",
        propositionC : "Utrzymanie tej samej predkosci",
        propositionD : "Wszystko bo moge ich odstrzelic",
        reponse : "C"},

  {   question : "Jedziesz autostrada, ktora wskazuje maksymalna prędkosc 120 kmh na godzine. Wiekszosc ruchu prowadzi z predkoscia 130 kmh, wiec nie powinienes jechac szybciej niz:",
        propositionA : "Nadal jestem rajdowcem i jade 269kmh",
        propositionB : "80 kmh",
        propositionC : "50 kmh",
        propositionD : "120 kmh",
        reponse : "D"},

  {   question : "Kiedy jestes wyprzedzany przez inny pojazd, NIE nalezy robic:",
        propositionA : "JESTEM RAJDOWCEM!!!!",
        propositionB : "Sprawdzac lusterek",
        propositionC : "Jechac tak samo jak teraz",
        propositionD : "Strzelac do wyprzedzajacego",
        reponse : "D"},
]
